Neoteroi/BlackSheep

- .gitignore
- blacksheep/baseapp.pyx
- blacksheep/utils/__init__.py
This is for #188
This enables falling back to the handler of a parent exception if one exists. When an exception inherits from multiple classes, we will for handlers from left to right. 
Example:
```python
class A():
pass
class B():
pass
class C(A, B): # If this is raised but doesn't have a handler, we will look for handler for A first and then B.
pass
class D(B, A): # If this is raised but doesn't have a handler, we will look for handler for B first and then A.
pass
```
Let me know if you would prefer the helper functions added in utils were in cypthon. This is my first experience with cython so I don't really know what are the trade-offs and what is at stake.
> Ability to set a single handler for all exceptions that inherit from a base exception

- requirements.txt
Only cchardet==2.1.7 supports Python3.9
ref: https://github.com/PyYoshi/cChardet/releases/tag/2.1.7
> Bump cchardet

- CHANGELOG.md
- README.md
- blacksheep/server/bindings.py
- blacksheep/server/controllers.py
- blacksheep/server/normalization.py
- blacksheep/server/openapi/common.py
- blacksheep/server/routing.py
- setup.py
- tests/test_bindings.py
- tests/test_controllers.py
- tests/test_normalization.py
- tests/test_router.py
* Prepares for v1.2.3 release
* [renames HTTPMethod to RouteMethod, supports sharing the same path for WebSocket and regular HTTP routes](https://github.com/Neoteroi/BlackSheep/commit/06d3916847fa961207c5f30174a4354717dd85f3)
* [refactors how name and type aliases are handled to obtain binders](https://github.com/Neoteroi/BlackSheep/commit/1702ad7cab2fdbbf1fa2d25e45523f40fc36b83f) - this is intended as internal API and won't be documented
~How WebSocket routes are documented in OpenAPI Documentation?~ WebSocket is not handled by OpenAPI Documentation specification. 
What happens now with the automatic generation of OpenAPI Documentation?
> v1.2.3 :cat2:

- CHANGELOG.md
- blacksheep/baseapp.pyx
- blacksheep/server/templating.py
- tests/test_application.py
- Adds support for configuring the Internal Server Error 500 handler for
unhandled exceptions (see #247)
- When configuring Jinja2 templates for the application, binds the `view`
function to `app.get_view_response` property
> Fix #247 (improvement)

- blacksheep/server/openapi/v3.py
fix for optional bool field when using BaseModel from Pydantic
Hi @RobertoPrevato, thank you for creating this great web framework.
I opened this PR to fix the problem I met when I was using Pydantic's BaseModel with openapi auto-generated docs.
The situation is like I have a model:
```python
from typing import Dict, List, Optional
from pydantic import AnyHttpUrl, BaseModel
class Params(BaseModel):
page_url: AnyHttpUrl
force_refresh: Optional[bool] = False
```
And if I ran the command 
```shell
http http://localhost:8000/openapi.json | jq .components.schemas.Params
```
I'll get
```JSON
{
"type": "object",
"required": [
"page_url",
"force_refresh"
],
"properties": {
"page_url": {
"type": "string",
"format": "uri",
"maxLength": 65536,
"minLength": 1,
"nullable": false
},
"force_refresh": { …
```
> 🐛 fix(openapi): fix for optional field for pydantic

- blacksheep/server/routing.py
- tests/test_openapi_v3.py
- tests/test_router.py
Sorry for the tenacity and bad english, but again about issue #286. The problem is that for routes with value patterns generated BAD schema. In spec: "Each template expression in the path MUST correspond to a path parameter that is included in the [Path Item](https://swagger.io/specification/#path-item-object) itself and/or in each of the Path Item's [Operations](https://swagger.io/specification/#operation-object)." BlackSheep make template expression "{uuid:image_id}", but path parameter name "image_id".
> Fix openapi scheme generation for routes with value patterns

- blacksheep/server/openapi/v3.py
- tests/test_openapi_v3.py
Tags ordering can be handled via tags description field [1]
```python
docs = OpenAPIHandler(
info=Info(title="Example API", version="0.0.1"),
tags=[
Tag(name="Users"),
Tag(name="Favorites"),
Tag(name="Reactions"),
Tag(name="Topics"),
Tag(name="Reviews"),
Tag(name="Comments"),
],
)
docs.bind_app(app)
```
For example, if a project has autogenerated tags in terms of using ApiController. OpenAPIHandler will automatically sort tags alphabetically.
```python
from dataclasses import dataclass
from blacksheep import Application
from blacksheep.server.controllers import APIController, get, post
from blacksheep.server.openapi.v3 import OpenAPIHandler
from openapidocs.v3 import Info
app = Application()
docs = OpenAPIHandler(info=Info(title="Example API", version="0.0.1"))
docs.bind_app(app) …
```
> Add description for tags

- blacksheep/server/openapi/common.py
- blacksheep/server/openapi/v3.py
- tests/test_openapi_v3.py
Add to APIDocsHandler __call__ security parameter
```python
@docs(
security=[
SecurityInfo("basicAuth", []),
SecurityInfo("bearerAuth", ["read:home", "write:home"]),
]
)
```
Add to OpenAPIHandler constructor security_schemes parameter
```python
docs = OpenAPIHandler(
info=Info(
title="Example API",
version="0.0.1",
),
security_schemes={
"oauth2": OAuth2Security(
flows=OAuthFlows(
implicit=OAuthFlow(
authorization_url="https://example.com/oauth2/authorize",
token_url="https://example.com/oauth2/token",
refresh_url="https://example.com/oauth2/refresh",
scopes={
"read:cats": "Read your cats",
"write:cats": "Write your cats",
},
)
),
description="OAuth2 Auth",
),
},
)
```
OpenAPI documentation - https://swagger.io/docs/specification/authentication/
> Support security defenition in OpenAPI docs

- blacksheep/server/rendering/jinja2.py
- tests/test_templating.py
Many editors and tools look for the `.html.jinja` extension in order to provide formatting, color highlighting, styling, intellisense, etc. To support those use cases, don't try to append the `.html` extension to templates that already specify the `.jinja` extension, and also do autoescaping for `.jinja` files.
I'm also open to making it ignore only `.html.jinja` instead of just `.jinja`, but that would force folks into using `.jinja.html` instead, which feels like an incorrect ext.
> add: support for jinja ext

- CHANGELOG.md
- blacksheep/__init__.py
- blacksheep/server/files/__init__.py
> Adds webp and webm to default extensions

- blacksheep/server/application.py
- blacksheep/server/websocket.py
- itests/app_2.py
- itests/test_server.py
- tests/test_websocket.py
@RobertoPrevato After some considerations, I decided to try this approach. Please, let me know, what you think about it. Is it good enough to you?
1. No matching WebSocket path? Close the connection, the ASGI server will respond with 403.
2. An exception raised during handshake? Close the connection, the ASGI server will respond with 403.
3. An exception raised after handshake? Close the connection with code 1011 (which seems to be equivalent to Internal Server Error, see https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4.1). We return the error reason too, but we take care to truncate it to prevent `control frame too long` errors.
We had a discussion about responding with a more precise status code if the connection was closed before accept, but it seems to be impossible in the ASGI …
> Fix WS exception handling

- blacksheep/server/res/swagger-ui.html
- itests/test_server.py
> upgrade SwaggerUI to version 5

- CHANGELOG.md
- README.md
- blacksheep/messages.pxd
- blacksheep/server/application.py
- blacksheep/server/normalization.py
- blacksheep/server/routing.py
- tests/test_websocket.py
- Removes the unused "active" property defined in the `Response` class.
- Fixes #455, reported by @Klavionik. This error caused the WebSocket handler to erroneously return an instance of BlackSheep response to the underlying ASGI server, causing an error to be logged in the console.
- Update type annotations in the `Application` class code to be more explicit about the fact that certain methods must return None (return in __call__ is used to interrupt code execution and not to return objects).
- Improve the normalization logic to not normalize the output for WebSocket requests (as ASGI servers do not allow controlling the response for WebSocket handshake requests).
- Improve the normalization logic to not normalize request handlers that are valid as they are, as asynchronous functions …
> Fix #455 and improve the normalization logic

- blacksheep/server/openapi/v3.py
- tests/test_openapi_v3.py
A possible solution to fix #474
> Pass annotated origin type to build OpenAPI docs

- blacksheep/testing/simulator.py
Adapt set_headers_for_response_content from scribe module to use it for TestSimulator
Issue #501
> Set content-type header in TestSimulator

- blacksheep/testing/client.py
- blacksheep/testing/simulator.py
- blacksheep/testing/websocket.py
- tests/test_websocket.py
Great package. TY for your hard work. I'm really enjoying blacksheep so far. But it feels like its missing a bit of WebSocket testing support.
Added starlette like WebSocket testing.
```python
from blacksheep import Application, WebSocket, ws
from blacksheep.testing import TestClient
app = Application()
@ws('/ws')
async def websocket_endpoint(websocket: WebSocket):
await websocket.accept()
await websocket.send_text('hello world')
@pytest.mark.asyncio
async def test_test_websocket():
await app.start()
client = TestClient(app)
async with client.websocket_connect('/ws') as websocket:
received = await websocket.receive_text()
assert received == 'hello world'
```
> feat: Added support for WebSocket in TestClient

- .github/workflows/main.yml
- blacksheep/asgi.pyi
- blacksheep/server/normalization.py
- blacksheep/server/openapi/v3.py
- blacksheep/server/resources.py
- blacksheep/utils/aio.py
- pyproject.toml
- requirements.txt
- tests/test_application.py
- tests/test_openapi_v3.py
Python 3.8 lifecycle has been stopped on 2024-10-07
> Drop python 3.8

- pyproject.toml
New version of essentials-openapi is available
> chore: update essentials-openapi to 1.1.0

- CHANGELOG.md
- blacksheep/baseapp.pyx
- blacksheep/server/normalization.py
- tests/test_application.py
- tests/test_controllers.py
- tests/utils/application.py
- Fix [#365](https://github.com/Neoteroi/BlackSheep/issues/365), adding support for
Pydantic's `@validate_call` and `@validate_arguments` and other wrappers applied to
functions before they are configured as request handlers.
Contribution by @aldem, who reported the issue and provided the solution.
- To better support `@validate_call`, automatically configures a default
exception handler for `pydantic.ValidationError` when Pydantic is installed.
> Fix/365 - improve support for Pydantic

- .github/workflows/perf.yml
- .gitignore
- perf/README.md
- perf/benchmarks/__init__.py
- perf/benchmarks/app.py
- perf/benchmarks/res/lorem.txt
- perf/benchmarks/url.py
- perf/benchmarks/writeresponse.py
- perf/genreport.py
- perf/historyrun.py
- perf/main.py
- perf/req.txt
- pytest.ini
- Add framework to measure code base performance. This is to refactor more comfortably Cython code and core features, keeping an eye on performance.
- Download the `benchmark-reports` artifact from the GitHub Workflow to see it in action. https://github.com/Neoteroi/BlackSheep/actions/runs/14950087869
> [!TIP]
>
> The `benchmark-reports` artifacts include Excel files with tables and charts.
>
>  [![Build](https://github.com/Neoteroi/BlackSheep/workflows/Benchmark/badge.svg)](https://github.com/Neoteroi/BlackSheep/actions/workflows/perf.yml)
> Add framework to measure code base performance ✨ 💎 

- blacksheep/utils/meta.py
This pull request fixes an issue in BlackSheep where **inherited controller handlers** lose argument type annotations and keyword-only defaults. For example, you can't have `POST` handlers that accept a typed request body and declare a return type (e.g., a Pydantic model).
---
BlackSheep supports **controller inheritance**, and the documentation includes an example with abstract base controllers:
```python
from blacksheep import Application
from blacksheep.server.controllers import Controller, abstract, get
app = Application()
@abstract()
class BaseController(Controller):
@get("/hello-world")
def index(self):
return self.text(f"Hello, World! {self.__class__.__name__}")
class ControllerOne(BaseController):
@classmethod
def route(cls) -> str:
return "/one"
```
In this example, the handlers …
> Fix: preserve annotations and kwdefaults in clonefunc for controller inheritance
